on: [push]

jobs:
  communicatie-engine-backend_job:
    runs-on: ubuntu-latest
    name: Build communicatie-engine-backend
    steps:
      - name: Echo something
        run: echo "Test Main"
      - name: Checkout
        uses: actions/checkout@v3   
      - name: DockerAction
        uses: ./
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1     
        with:       
            username: ${{ secrets.DOCKER_HUB_USER }} 
            password:  ${{ secrets.DOCKER_HUB_PASSWORD }}
            repository: christopietersealliander/test    
            tags: ${{github.run_number}}