on: [push]

jobs:
  communicatie-engine-backend_job:
    runs-on: ubuntu-latest
    name: Build communicatie-engine-backend
    steps:
      - name: Echo something
        run: echo "Test Main"
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Java version
        run: java -version        
      - name: Checkout
        uses: actions/checkout@v3 
      - name: mvn install
        run: mvn install -DskipTests 
      - name: DockerAction
        uses: ./
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1     
        with:       
            username: ${{ secrets.DOCKER_HUB_USER }} 
            password:  ${{ secrets.DOCKER_HUB_PASSWORD }}
            repository: christopietersealliander/test    
            tags: ${{github.run_number}}
