on: [push]

jobs:
  communicatie-engine-backend_job:
    runs-on: ubuntu-latest
    name: Build communicatie-engine-backend
    steps:
      - name: Hello world action step
        id: hello
        uses: maven-build-action
      - name: Echo something
        run: echo "Test Main"