on: [push]

jobs:
  communicatie-engine-backend_job:
    runs-on: ubuntu-latest
    name: Build communicatie-engine-backend
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/maven-build-action@v2
      - name: Echo something
        run: echo "Test Main"