on: [push]

jobs:
  communicatie-engine-backend_job:
    runs-on: ubuntu-latest
    name: 'mvn build'
    steps:
      - name: Java version
        run: java -version
      - name: Checkout
        uses: actions/checkout@v3        
      - name: Echo 1
        run: echo "Going to call mvn"
      - name: mvn install
        run: mvn install -DskipTests
      - name: Echo 2
        run: echo "Maven is done!"
